Add anomaly detection example
aws-samples/amazon-kinesis-data-analytics-examples pull request #57
Opened 2023-03-16 16:24 UTC by antovespoli

*Description of changes:*
Add a code example for a streaming anomaly detection algorithm based on left-discords.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-03-22 17:34 UTC, dannycranmer commented
Where did you get the binary files `AnomalyDetection/LeftDiscords/datasets/castironToSteel_36760.mat` and `AnomalyDetection/LeftDiscords/datasets/97.mat` from? How are they licensed?

2023-03-22 17:34 UTC, dannycranmer requested changes

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/pom.xml
> +        <flink.version>1.15.2</flink.version>
Please bump to 1.15.4 since it contains critical bug fixes

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/pom.xml
> +                <artifactId>aws-java-sdk-bom</artifactId>
Why are we using SDK v1 instead of v2?

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/pom.xml
> +        </dependency>
This is not required since it is transitive from `flink-connector-kinesis`

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/src/main/java/software/amazon/com/MPStreamingJob.java
> +        env.disableOperatorChaining();
Why? This can impact performance, if this is not explicitly required please remove

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/src/main/java/software/amazon/com/MPStreamingJob.java
> +        inputProperties.setProperty(ConsumerConfigConstants.STREAM_INITIAL_POSITION, "LATEST");
This is the default, not required

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/pom.xml
> +        </dependency>
I cannot see this used anywhere, can we remove?

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/src/main/java/software/amazon/com/MPProcessFunction.java
> +package software.amazon.com;
Missing copyright headers, check all files

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/pom.xml
> +    <groupId>software.amazon.com</groupId>
This looks wrong, the `com` is usually at the start. Can we change to `software.amazon.flink.example` inline with https://github.com/aws-samples/amazon-kinesis-data-analytics-examples/blob/master/cloudwatch-async-sink-example/pom.xml#L25?

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/pom.xml
> +    <version>1.0.0-SNAPSHOT</version>
Bump to final version for release

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/src/main/java/software/amazon/com/MPProcessFunction.java
> +        timeSeriesData.add(record);
Should this not be stateful? We will drop `timeSeriesData` on failure right?

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/src/main/java/software/amazon/com/MPProcessFunction.java
> +        collector.collect(output.toString());
This is sloppy, why not output a POJO and serialize in the sink via `SerializationSchema`?

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/src/main/java/software/amazon/com/MPProcessFunction.java
> +        currentIndex += 1;
Does this need to go into operator state?

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/src/main/java/software/amazon/com/Threshold.java
> +    int counter;
Scope to `private`

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/src/main/java/software/amazon/com/Threshold.java
> +        this.counter = 0;
Why not just initialise in the declaration?

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/src/main/java/software/amazon/com/Threshold.java
> +        sum = sum + record;
nit: `sum += record` ..

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/src/main/java/software/amazon/com/Threshold.java
> +        return mean + 2 * Math.sqrt(squaredSum/counter - mean*mean);
nit: Spacing around division and multiplication

2023-03-22 17:34 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/src/main/java/software/amazon/com/TimeSeries.java
> +    private final ArrayList<Double> contextWindow;
Change `ArrayList` to `List`

2023-03-28 07:59 UTC, dannycranmer requested changes

2023-03-28 07:59 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/pom.xml
> +    <artifactId>matrixProfile</artifactId>
maven artifacts are typically `matrix-profile`

2023-03-28 07:59 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/pom.xml
> +                <version>2.x.x</version>
nit: Not seen this notation before, assume it always pulls the latest? This could break something later, but not too strongly opinionated here

2023-03-28 07:59 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/src/main/java/software/amazon/flink/example/OutputWithLabel.java
> +    public Double input;
Why using `Double` and not `double` ?

2023-04-18 08:26 UTC, dannycranmer requested changes

2023-04-18 08:26 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/README.md
> +A left-discord is a subsequence that is significantly dissimilar from all the sub sequences that precede it. In this sample, we demonstrate how to use the concept of left-discords to identify time-se
nit: First reference should use the marketing name "Amazon Kinesis Data Analytics". Nit because I am not sure how this applies to README

2023-04-18 08:26 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/pom.xml
> +    <artifactId>matrix-profile</artifactId>
Should this be `left-discords` since the module name usually reflects the module folder?

2023-04-18 08:26 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/src/main/java/software/amazon/flink/example/MPProcessFunction.java
> +        Double record = Double.parseDouble(dataPoint);
Why use `Double` and not `double`?

2023-04-18 08:26 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/pom.xml
> +        <kda.runtime.version>1.2.0</kda.runtime.version>
This is not used

2023-04-18 08:26 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/src/main/java/software/amazon/flink/example/MPProcessFunction.java
> +public class MPProcessFunction extends ProcessFunction<String, OutputWithLabel> implements CheckpointedFunction {
nit: There are a lot of magic numbers/string in this class, consider extracting to static constants

2023-04-18 08:26 UTC, dannycranmer commented on AnomalyDetection/LeftDiscords/core/src/main/java/software/amazon/flink/example/Threshold.java
> +    private Double squaredSum = 0.0;
use `double` since we are not expecting `null`

2023-05-16 16:34 UTC, spaethp approved these changes

2023-05-19 08:24 UTC, merged